### ISSUE TITLE
Which version should I use

### ISSUE THREAD

**Issue by user24816** [leleuj/cas-overlay-demo#14]
When building master branch there was error: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]

I know there a bug for that error, so I tried branch 4.2.x and got different error: [ERROR] Failed to execute goal on project cas-overlay-server-demo: Could not resolve dependencies for project org.leleuj
:cas-overlay-server-demo:war:4.2.0-SNAPSHOT: Failure to find org.jasig.cas:cas-server-integration-restlet:jar:4.2.0-RC2
in https://build.shibboleth.net/nexus/content/groups/public was cached in the local repository, resolution will not be r
eattempted until the update interval of shibboleth-public-repo has elapsed or updates are forced -> [Help 1]

Which version is working right now?

**Comment by leleuj** [comment]
You should use the 4.2.x branch to have a stable version? Master still needs to be updated to accommodate the new SpringBoot CAS v5.0.

**Comment by jorgefdez205** [comment]
Hi leleuj, 

I have the same Issue of restlet dependency, but I don't know why you closed this thread, because I'm not able to compile the project because I get the same error in every attempt (with 4.2.x branch)...

Can you help me with this:

[ERROR] Failed to execute goal on project cas-overlay-server-demo: Could not resolve dependencies for project org.leleuj:cas-overlay-server-demo:war:4.2.0-SNAPSHOT: Could not find artifact org.jasig.cas:cas-server-integration-restlet:jar:4.2.0

Thanks
